# Script (Python) "hazardous"
# bind container=container
# bind context=context
# bind namespace=
# bind script=script
# bind subpath=traverse_subpath
# parameters=language
# title=
##
return """<?xml version="1.0" encoding="UTF-8"?>  # noqa: F999
<hazardous 
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
      xmlns:xi="http://www.w3.org/2001/XInclude"
      xsi:noNamespaceSchemaLocation="http://biodiversity.eionet.europa.eu/schemas/barcelona_convention/hazardous.xsd"  # noqa: E501
      xml:lang="%s">
  <reporting-party>
    <contracting-party/>
    <reporting-period-start/>
    <reporting-period-end/>
    <institution-name-full/>
    <officer-name-focalpoint/>
    <mailing-address/>
    <telephone/>
    <fax/>
    <email/>
    <contact-point-national>
      <contact-point/>
      <institution-full-name/>
      <mailing-address/>
      <telephone/>
      <fax/>
      <email/>
    </contact-point-national>
    <signature/>
    <submission-date/>
    <providers>
      <provider>
        <institution-full-name/>
        <contact-point-name/>
        <mailing-address/>
        <telephone/>
        <fax/>
        <email/>
      </provider>
    </providers>
  </reporting-party>
  <report>
    <legal-measures>
      <table>
        <wastes-reduction>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </wastes-reduction>
        <transboundary-movement>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </transboundary-movement>
        <sea-transit-movement>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </sea-transit-movement>
        <sea-territorial-movement>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </sea-territorial-movement>
        <sea-import-export-notification>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </sea-import-export-notification>
        <sea-export-transit-notification>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </sea-export-transit-notification>
        <prevention-punishment>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </prevention-punishment>
      </table>
    </legal-measures>
    <resource-allocation>
      <table>
        <art6-12>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </art6-12>
        <identify-punish>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </identify-punish>
      </table>
    </resource-allocation>
    <technical-data>
      <table>
        <row>
          <description/>
          <definition/>
          <characteristics/>
          <movement/>
        </row>
      </table>
      <table2>
        <row>
          <year/>
          <hazardous-wastes-generated/>
          <other-wastes/>
        </row>
      </table2>
      <remark/>
      <table3>
        <row>
          <year/>
          <y1/>
          <y2/>
          <y3/>
          <y4/>
          <y5/>
          <y6/>
          <y7/>
          <y8/>
          <y9/>
          <y10/>
          <y11/>
          <y12/>
          <y13/>
          <y14/>
          <y15/>
          <y16/>
          <y17/>
          <y18/>
          <y19/>
          <y20/>
          <y21/>
          <y22/>
          <y23/>
          <y24/>
          <y25/>
          <y26/>
          <y27/>
          <y28/>
          <y29/>
          <y30/>
          <y31/>
          <y32/>
          <y33/>
          <y34/>
          <y35/>
          <y36/>
          <y37/>
          <y38/>
          <y39/>
          <y40/>
          <y41/>
          <y42/>
          <y43/>
          <y44/>
          <y45/>
          <y46/>
          <y47/>
        </row>
      </table3>
      <waste-exported>
        <exported/>
        <exported-ia/>
        <exported-ib/>
        <exported-other/>
      </waste-exported>
      <table4-1>
        <row>
          <waste-category>
            <annex1>
              <y-code/>
              <streams/>
            </annex1>
            <annex8/>
          </waste-category>
          <hazardous-characteristics>
            <un/>
            <h/>
            <characteristics/>
          </hazardous-characteristics>
          <exported/>
          <transit/>
          <destination/>
          <disposal/>
          <recovery/>
        </row>
      </table4-1>
      <waste-imported>
        <imported-ia/>
        <imported-ib/>
        <imported-other/>
      </waste-imported>
      <table4-2>
        <row>
          <waste-category>
            <annex1>
              <y-code/>
              <streams/>
            </annex1>
            <annex8/>
          </waste-category>
          <hazardous-characteristics>
            <un/>
            <h/>
            <characteristics/>
          </hazardous-characteristics>
          <exported/>
          <transit/>
          <destination/>
          <disposal/>
          <recovery/>
        </row>
      </table4-2>
      <table4-3>
        <row>
          <waste/>
          <quantity/>
          <remarks/>
        </row>
      </table4-3>
      <table5>
        <row>
          <accidents/>
          <measures/>
          <effectiveness/>
        </row>
      </table5>
      <art8-3>
        <row>
          <alternative-options/>
          <description/>
        </row>
      </art8-3>
    </technical-data>
    <enforcement-measures>
      <table>
        <inspections/>
        <contraventions/>
        <sanctions/>
        <other-measures/>
        <clean-measures/>
        <remarks/>
      </table>
    </enforcement-measures>
    <effectiveness>
      <wastes-generated/>
      <wastes-imported/>
      <wastes-exported/>
      <inspections/>
      <contraventions/>
      <contraventions-sanctioned/>
    </effectiveness>
  </report>
</hazardous>
"""
