## Script (Python) "lbs"
##bind container=container
##bind context=context
##bind namespace=
##bind script=script
##bind subpath=traverse_subpath
##parameters=language
##title=
##
return """<?xml version="1.0" encoding="UTF-8"?>
<lbs 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xmlns:xi="http://www.w3.org/2001/XInclude"
    xsi:noNamespaceSchemaLocation="http://biodiversity.eionet.europa.eu/schemas/barcelona_convention/lbs.xsd" 
    xml:lang="%s">
 <reporting-party>
    <contracting-party/>
    <reporting-period-start/>
    <reporting-period-end/>
    <institution-name-full/>
    <officer-name-focalpoint/>
    <mailing-address/>
    <telephone/>
    <fax/>
    <email/>
    <contact-point-national>
      <contact-point/>
      <institution-full-name/>
      <mailing-address/>
      <telephone/>
      <fax/>
      <email/>
    </contact-point-national>
    <signature/>
    <submission-date/>
    <providers>
      <provider>
        <institution-full-name/>
        <contact-point-name/>
        <mailing-address/>
        <telephone/>
        <fax/>
        <email/>
      </provider>
    </providers>
  </reporting-party>
  <report>
    <legal-measures>
      <table>
        <eliminate-lbs-pollution>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </eliminate-lbs-pollution>
        <accidental-pollution>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </accidental-pollution>
        <point-source-discharges>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </point-source-discharges>
        <inspection-systems>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </inspection-systems>
        <sanctions>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </sanctions>
        <common-measures>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </common-measures>
      </table>
    </legal-measures>
    <resource-allocation>
      <table>
        <permits-issuing>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </permits-issuing>
        <inspection-structures>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </inspection-structures>
        <monitoring-structures>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </monitoring-structures>
        <monitoring-programmes>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </monitoring-programmes>
      </table>
    </resource-allocation>    
    <administrative-measures>
      <table3-1>
        <energy>
          <ongoing-authorizations/>
          <point-sources/>
          <new-authorizations/>
          <new-point-sources/>
          <percent-authorizations/>
          <percent-new-point-sources/>
          <released-substances/>
        </energy>
        <fertilizer>
          <ongoing-authorizations/>
          <point-sources/>
          <new-authorizations/>
          <new-point-sources/>
          <percent-authorizations/>
          <percent-new-point-sources/>
          <released-substances/>
        </fertilizer>
        <biocides>
          <ongoing-authorizations/>
          <point-sources/>
          <new-authorizations/>
          <new-point-sources/>
          <percent-authorizations/>
          <percent-new-point-sources/>
          <released-substances/>
        </biocides>
        <pharmaceutical>
          <ongoing-authorizations/>
          <point-sources/>
          <new-authorizations/>
          <new-point-sources/>
          <percent-authorizations/>
          <percent-new-point-sources/>
          <released-substances/>
        </pharmaceutical>
        <petroleum>
          <ongoing-authorizations/>
          <point-sources/>
          <new-authorizations/>
          <new-point-sources/>
          <percent-authorizations/>
          <percent-new-point-sources/>
          <released-substances/>
        </petroleum>
        <paper>
          <ongoing-authorizations/>
          <point-sources/>
          <new-authorizations/>
          <new-point-sources/>
          <percent-authorizations/>
          <percent-new-point-sources/>
          <released-substances/>
        </paper>
        <cement>
          <ongoing-authorizations/>
          <point-sources/>
          <new-authorizations/>
          <new-point-sources/>
          <percent-authorizations/>
          <percent-new-point-sources/>
          <released-substances/>
        </cement>
        <tanning>
          <ongoing-authorizations/>
          <point-sources/>
          <new-authorizations/>
          <new-point-sources/>
          <percent-authorizations/>
          <percent-new-point-sources/>
          <released-substances/>
        </tanning>
        <metal>
          <ongoing-authorizations/>
          <point-sources/>
          <new-authorizations/>
          <new-point-sources/>
          <percent-authorizations/>
          <percent-new-point-sources/>
          <released-substances/>
        </metal>
        <mining>
          <ongoing-authorizations/>
          <point-sources/>
          <new-authorizations/>
          <new-point-sources/>
          <percent-authorizations/>
          <percent-new-point-sources/>
          <released-substances/>
        </mining>
        <shipbuilding>
          <ongoing-authorizations/>
          <point-sources/>
          <new-authorizations/>
          <new-point-sources/>
          <percent-authorizations/>
          <percent-new-point-sources/>
          <released-substances/>
        </shipbuilding>
        <harbour>
          <ongoing-authorizations/>
          <point-sources/>
          <new-authorizations/>
          <new-point-sources/>
          <percent-authorizations/>
          <percent-new-point-sources/>
          <released-substances/>
        </harbour>
        <textile>
          <ongoing-authorizations/>
          <point-sources/>
          <new-authorizations/>
          <new-point-sources/>
          <percent-authorizations/>
          <percent-new-point-sources/>
          <released-substances/>
        </textile>
        <electronics>
          <ongoing-authorizations/>
          <point-sources/>
          <new-authorizations/>
          <new-point-sources/>
          <percent-authorizations/>
          <percent-new-point-sources/>
          <released-substances/>
        </electronics>
        <recycling>
          <ongoing-authorizations/>
          <point-sources/>
          <new-authorizations/>
          <new-point-sources/>
          <percent-authorizations/>
          <percent-new-point-sources/>
          <released-substances/>
        </recycling>
        <inorganic>
          <ongoing-authorizations/>
          <point-sources/>
          <new-authorizations/>
          <new-point-sources/>
          <percent-authorizations/>
          <percent-new-point-sources/>
          <released-substances/>
        </inorganic>
        <tourism>
          <ongoing-authorizations/>
          <point-sources/>
          <new-authorizations/>
          <new-point-sources/>
          <percent-authorizations/>
          <percent-new-point-sources/>
          <released-substances/>
        </tourism>
        <agriculture>
          <ongoing-authorizations/>
          <point-sources/>
          <new-authorizations/>
          <new-point-sources/>
          <percent-authorizations/>
          <percent-new-point-sources/>
          <released-substances/>
        </agriculture>
        <animal>
          <ongoing-authorizations/>
          <point-sources/>
          <new-authorizations/>
          <new-point-sources/>
          <percent-authorizations/>
          <percent-new-point-sources/>
          <released-substances/>
        </animal>
        <food>
          <ongoing-authorizations/>
          <point-sources/>
          <new-authorizations/>
          <new-point-sources/>
          <percent-authorizations/>
          <percent-new-point-sources/>
          <released-substances/>
        </food>
        <aquaculture>
          <ongoing-authorizations/>
          <point-sources/>
          <new-authorizations/>
          <new-point-sources/>
          <percent-authorizations/>
          <percent-new-point-sources/>
          <released-substances/>
        </aquaculture>
        <hazardous-wastes>
          <ongoing-authorizations/>
          <point-sources/>
          <new-authorizations/>
          <new-point-sources/>
          <percent-authorizations/>
          <percent-new-point-sources/>
          <released-substances/>
        </hazardous-wastes>
        <wastewater>
          <ongoing-authorizations/>
          <point-sources/>
          <new-authorizations/>
          <new-point-sources/>
          <percent-authorizations/>
          <percent-new-point-sources/>
          <released-substances/>
        </wastewater>
        <solid-waste>
          <ongoing-authorizations/>
          <point-sources/>
          <new-authorizations/>
          <new-point-sources/>
          <percent-authorizations/>
          <percent-new-point-sources/>
          <released-substances/>
        </solid-waste>
        <sewage>
          <ongoing-authorizations/>
          <point-sources/>
          <new-authorizations/>
          <new-point-sources/>
          <percent-authorizations/>
          <percent-new-point-sources/>
          <released-substances/>
        </sewage>
        <waste-management>
          <ongoing-authorizations/>
          <point-sources/>
          <new-authorizations/>
          <new-point-sources/>
          <percent-authorizations/>
          <percent-new-point-sources/>
          <released-substances/>
        </waste-management>
        <coastline-alteration>
          <ongoing-authorizations/>
          <point-sources/>
          <new-authorizations/>
          <new-point-sources/>
          <percent-authorizations/>
          <percent-new-point-sources/>
          <released-substances/>
        </coastline-alteration>
        <transport>
          <ongoing-authorizations/>
          <point-sources/>
          <new-authorizations/>
          <new-point-sources/>
          <percent-authorizations/>
          <percent-new-point-sources/>
          <released-substances/>
        </transport>
      </table3-1>
      <table3-2>
        <organohalogen/>
        <organophosphorus/>
        <organotin/>
        <polycyclic/>
        <heavy-metals/>
        <lubricating-oils/>
        <radioactive/>
        <biocides/>
        <crude-oils/>
        <cyanides-fluorides/>
        <detergents/>
        <nitrogen-phosphorus/>
        <litter/>
        <acid-alkaline/>
        <non-toxic-oxygen/>
        <non-toxic-seawater/>
      </table3-2>
      <table4>
        <national>
          <inspections/>
          <non-compliance/>
          <fines/>
          <suspensions/>
          <shutdowns/>
          <other-measures/>
          <clean-measures/>
          <remarks/>
        </national>
        <specific-conditions>
          <inspections/>
          <non-compliance/>
          <fines/>
          <suspensions/>
          <shutdowns/>
          <other-measures/>
          <clean-measures/>
          <remarks/>
        </specific-conditions>
      </table4>
    </administrative-measures>
    <nap-implementation>
      <priorities>
        <status-column>
          <status-type/>
          <reference/>
          <comment/>
        </status-column>
        <difficulties-column>
          <difficulty-type/>
          <comment/>
        </difficulties-column>
      </priorities>
    </nap-implementation>
    <monitoring-programmes>
      <state-trend>
        <status-column>
          <status-type/>
          <reference/>
          <comment/>
        </status-column>
        <difficulties-column>
          <difficulty-type/>
          <comment/>
        </difficulties-column>
      </state-trend>
      <compliance>
        <status-column>
          <status-type/>
          <reference/>
          <comment/>
        </status-column>
        <difficulties-column>
          <difficulty-type/>
          <comment/>
        </difficulties-column>
      </compliance>
      <biomonitoring>
        <status-column>
          <status-type/>
          <reference/>
          <comment/>
        </status-column>
        <difficulties-column>
          <difficulty-type/>
          <comment/>
        </difficulties-column>
      </biomonitoring>
      <eutrophication>
        <status-column>
          <status-type/>
          <reference/>
          <comment/>
        </status-column>
        <difficulties-column>
          <difficulty-type/>
          <comment/>
        </difficulties-column>
      </eutrophication>
    </monitoring-programmes>
    <effectiveness>
      <authorizations/>
      <pollution-sectors/>
      <pollution-substances/>
      <projects-completed/>
      <inspections/>
      <non-compliance/>
      <non-compliance-sanctioned/>
    </effectiveness>
  </report>
</lbs>
"""
