## Script (Python) "prevention"
##bind container=container
##bind context=context
##bind namespace=
##bind script=script
##bind subpath=traverse_subpath
##parameters=language
##title=
##
return """<?xml version="1.0" encoding="UTF-8"?>
<prevention
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
      xmlns:xi="http://www.w3.org/2001/XInclude"
      xsi:noNamespaceSchemaLocation="http://biodiversity.eionet.europa.eu/schemas/barcelona_convention/prevention.xsd" 
      xml:lang="%s">
  <reporting-party>
    <contracting-party/>
    <reporting-period-start/>
    <reporting-period-end/>
    <institution-name-full/>
    <officer-name-focalpoint/>
    <mailing-address/>
    <telephone/>
    <fax/>
    <email/>
    <contact-point-national>
      <contact-point/>
      <institution-full-name/>
      <mailing-address/>
      <telephone/>
      <fax/>
      <email/>
    </contact-point-national>
    <signature/>
    <submission-date/>
    <providers>
      <provider>
        <institution-full-name/>
        <contact-point-name/>
        <mailing-address/>
        <telephone/>
        <fax/>
        <email/>
      </provider>
    </providers>
  </reporting-party>
  <report>
    <ratification-status>
      <table>
        <load-lines>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </load-lines>
        <safety-sea-life>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </safety-sea-life>
        <pollution-from-ships>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </pollution-from-ships>
        <training-standards>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </training-standards>
        <collisions>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </collisions>
        <tonnage-measurements>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </tonnage-measurements>
        <merchant-shipping>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </merchant-shipping>
        <antifouling-systems>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </antifouling-systems>
      </table>
      <table2>
        <oil-pollution>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </oil-pollution>
        <oil-pollution-casualties>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </oil-pollution-casualties>
        <salvage-convention>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </salvage-convention>
      </table2>
      <table3>
        <oil-pollution-damage>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </oil-pollution-damage>
        <compensation-fund>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </compensation-fund>
        <compensation-hazardous>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </compensation-hazardous>
        <bunker-oil-pollution>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </bunker-oil-pollution>
      </table3>
    </ratification-status>
    <legal-measures>
      <table>
        <contingency-plans>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </contingency-plans>
        <combating-equipment>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </combating-equipment>
        <personnel-training>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </personnel-training>
        <responsible-authorities>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </responsible-authorities>
        <state-authorities>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </state-authorities>
        <regional-centre-update>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </regional-centre-update>
        <monitoring-activities>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </monitoring-activities>
        <dissemination-organisation>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </dissemination-organisation>
        <dissemination-authorities>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </dissemination-authorities>
        <dissemination-state-authorities>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </dissemination-state-authorities>
        <dissemination-ship-pollution>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </dissemination-ship-pollution>
        <dissemination-preparedness>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </dissemination-preparedness>
        <dissemination-new-ways>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </dissemination-new-ways>
        <regional-centre>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </regional-centre>
        <communication-bilateral>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </communication-bilateral>
        <port-reception>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </port-reception>
        <port-reception-efficiency>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </port-reception-efficiency>
        <update-ships>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </update-ships>
        <assess-route-risks>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </assess-route-risks>
        <reducing-accidents-risks>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </reducing-accidents-risks>
        <reception-strategies>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </reception-strategies>
      </table>
    </legal-measures>
    <technical-measures>
      <table5>
        <response-strategy>
          <answer/>
          <remarks/>
        </response-strategy>
        <ncp-substances>
          <answer/>
          <remarks/>
        </ncp-substances>
        <anti-pollution-equipment-stockpile>
          <answer/>
          <remarks/>
        </anti-pollution-equipment-stockpile>
        <exercices>
          <answer/>
          <remarks/>
        </exercices>
        <local-port-contingency-plan>
          <answer/>
          <remarks/>
        </local-port-contingency-plan>
        <local-plan-integrated-ncp>
          <answer/>
          <remarks/>
        </local-plan-integrated-ncp>
        <local-plan-integrated-industry>
          <answer/>
          <remarks/>
        </local-plan-integrated-industry>
        <ships-emergency-plan>
          <answer/>
          <remarks/>
        </ships-emergency-plan>
        <country-requested-plan>
          <answer/>
          <remarks/>
        </country-requested-plan>
        <country-requested-contingency-plan>
          <answer/>
          <remarks/>
        </country-requested-contingency-plan>
        <subregional-agreements>
          <answer/>
          <remarks/>
          <ncp-reference/>
          <ncp-date/>
          <comments/>
          <bilateral-agreements/>
          <subregional-agreements/>
        </subregional-agreements>
        <framework-exercices>
          <answer/>
          <dates/>
          <remarks/>
          <exercise/>
          <comments/>
        </framework-exercices>
      </table5>
      <table6>
        <communication-means>
          <answer/>
          <impediments/>
          <remedy/>
          <actions/>
        </communication-means>
        <instruction-ship-masters>
          <answer/>
          <impediments/>
          <remedy/>
          <actions/>
        </instruction-ship-masters>
        <information-collection>
          <answer/>
          <impediments/>
          <remedy/>
          <actions/>
        </information-collection>
        <information-collected-shared>
          <answer/>
          <impediments/>
          <remedy/>
          <actions/>
        </information-collected-shared>
      </table6>
    </technical-measures>
    <spill-incidents>
      <table>
        <row>
          <location/>
          <type/>
          <vesselno/>
          <flag/>
          <product-released/>
          <product-type/>
          <action-taken/>
          <action/>
        </row>
      </table>
    </spill-incidents>
    <effectiveness/>
  </report>
</prevention>
"""
