return """<?xml version="1.0" encoding="UTF-8"?>
<spa-biodiversity
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
      xmlns:xi="http://www.w3.org/2001/XInclude"
      xsi:noNamespaceSchemaLocation="http://biodiversity.eionet.europa.eu/schemas/barcelona_convention/spa-biodiversity.xsd" 
      xml:lang="%s">
  <reporting-party>
    <contracting-party/>
    <reporting-period-start/>
    <reporting-period-end/>
    <institution-name-full/>
    <officer-name-focalpoint/>
    <mailing-address/>
    <telephone/>
    <fax/>
    <email/>
    <contact-point-national>
      <contact-point/>
      <institution-full-name/>
      <mailing-address/>
      <telephone/>
      <fax/>
      <email/>
    </contact-point-national>
    <signature/>
    <submission-date/>
    <providers>
      <provider>
        <institution-full-name/>
        <contact-point-name/>
        <mailing-address/>
        <telephone/>
        <fax/>
        <email/>
      </provider>
    </providers>
  </reporting-party>
  <report>
    <legal-measures>
      <table>
        <terrestrial-areas>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </terrestrial-areas>
        <endangered-species>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </endangered-species>
        <spa-management>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </spa-management>
        <spa-dumping>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </spa-dumping>
        <spa-passage>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </spa-passage>
        <spa-exploration>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </spa-exploration>
        <spa-research>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </spa-research>
        <spa-species-collection>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </spa-species-collection>
        <spa-adverse-activities>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </spa-adverse-activities>
        <spa-species-conservation>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </spa-species-conservation>
        <spa-habitats>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </spa-habitats>
      </table>
    </legal-measures>
    <spa>
      <table2>
        <geographical-coverage>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </geographical-coverage>
        <spa-management-plan>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </spa-management-plan>
      </table2>
      <table3>
        <table3-row>
          <spa-name/>
          <created/>
          <category/>
          <jurisdiction/>
          <coordinates/>
          <surface/>
          <main-ecosystems/>
          <management-plan>
            <adopted/>
            <no/>
            <under-devel/>
          </management-plan>
        </table3-row>
      </table3>
      <table4>
        <spa-monitoring>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </spa-monitoring>
        <local-communities>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </local-communities>
        <inhabitant-assistance>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </inhabitant-assistance>
        <fund-compatible-activities>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </fund-compatible-activities>
        <training>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </training>
        <national-plan>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </national-plan>
        <institutional-arrangement>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </institutional-arrangement>
      </table4>
    </spa>
    <spamis>
      <table5>
        <setup>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </setup>
        <management-plan>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </management-plan>
      </table5>
      <table6>
        <row>
          <name/>
          <created/>
          <coordinates/>
          <jurisdiction>
            <national/>
            <adjacent/>
            <high-seas/>
          </jurisdiction>
          <management>
            <adoption/>
            <no/>
            <in-process/>
          </management>
          <delimitation/>
          <legal-status/>
          <reasons/>
        </row>
      </table6>
      <table7>
        <row>
          <no-spami/>
          <surface/>
          <regulation>
            <dumping/>
            <monitoring/>
            <species/>
            <harmful-activities/>
            <buffer-zone-activities/>
          </regulation>
          <difficulties-column>
            <difficulty-type/>
          </difficulties-column>
          <delimitation/>
          <legal-status/>
          <reasons/>
        </row>
      </table7>
    </spamis>
    <protection-measures>
      <table8>
        <threatened-species>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </threatened-species>
        <cooperation>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </cooperation>
        <ex-situ-reproduction>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </ex-situ-reproduction>
        <exteptions>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </exteptions>
        <non-native-species>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </non-native-species>
      </table8>
      <table9>
        <row>
          <species-list/>
          <endangered-species/>
          <migrant-species/>
          <ex-situ-measures/>
          <extemption-granted/>
          <species-introduction/>
          <remarks/>
        </row>
      </table9>
    </protection-measures>
    <conservation>
      <table10>
        <inventory>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </inventory>
        <national-strategy>
          <status-column>
            <status-type/>
            <reference/>
            <comment/>
          </status-column>
          <difficulties-column>
            <difficulty-type/>
            <comment/>
          </difficulties-column>
        </national-strategy>
      </table10>
    </conservation>
    <enforcement-measures>
      <table11>
        <species-activities>
          <inspections/>
          <non-compliance/>
          <fines/>
          <enforcements/>
          <remarks/>
        </species-activities>
        <article11-3>
          <inspections/>
          <non-compliance/>
          <fines/>
          <enforcements/>
          <remarks/>
        </article11-3>
        <article11-5>
          <inspections/>
          <non-compliance/>
          <fines/>
          <enforcements/>
          <remarks/>
        </article11-5>
      </table11>
    </enforcement-measures>
    <effectiveness>
      <spas/>
      <spas-surface/>
      <spas-managed/>
      <spami/>
      <species/>
      <species-endangered/>
      <inspections/>
      <non-compliance/>
      <non-compliance-sanctioned/>
      <cartilaginous-fish>
        <table>
          <human>
            <status-column>
              <status-type/>
              <reference/>
              <comment/>
            </status-column>
            <difficulties-column>
              <difficulty-type/>
              <comment/>
            </difficulties-column>
          </human>
          <ipoa-sharks>
            <status-column>
              <status-type/>
              <reference/>
              <comment/>
            </status-column>
            <difficulties-column>
              <difficulty-type/>
              <comment/>
            </difficulties-column>
          </ipoa-sharks>
          <fishing>
            <status-column>
              <status-type/>
              <reference/>
              <comment/>
            </status-column>
            <difficulties-column>
              <difficulty-type/>
              <comment/>
            </difficulties-column>
          </fishing>
          <research-chondrichthyans>
            <status-column>
              <status-type/>
              <reference/>
              <comment/>
            </status-column>
            <difficulties-column>
              <difficulty-type/>
              <comment/>
            </difficulties-column>
          </research-chondrichthyans>
          <training>
            <status-column>
              <status-type/>
              <reference/>
              <comment/>
            </status-column>
            <difficulties-column>
              <difficulty-type/>
              <comment/>
            </difficulties-column>
          </training>
          <information>
            <status-column>
              <status-type/>
              <reference/>
              <comment/>
            </status-column>
            <difficulties-column>
              <difficulty-type/>
              <comment/>
            </difficulties-column>
          </information>
        </table>
      </cartilaginous-fish>
      <non-indigenous-species>
        <table>
          <legislation>
            <status-column>
              <status-type/>
              <reference/>
              <comment/>
            </status-column>
            <difficulties-column>
              <difficulty-type/>
              <comment/>
            </difficulties-column>
          </legislation>
          <assessment>
            <status-column>
              <status-type/>
              <reference/>
              <comment/>
            </status-column>
            <difficulties-column>
              <difficulty-type/>
              <comment/>
            </difficulties-column>
          </assessment>
          <monitoring>
            <status-column>
              <status-type/>
              <reference/>
              <comment/>
            </status-column>
            <difficulties-column>
              <difficulty-type/>
              <comment/>
            </difficulties-column>
          </monitoring>
          <action>
            <status-column>
              <status-type/>
              <reference/>
              <comment/>
            </status-column>
            <difficulties-column>
              <difficulty-type/>
              <comment/>
            </difficulties-column>
          </action>
          <training>
            <status-column>
              <status-type/>
              <reference/>
              <comment/>
            </status-column>
            <difficulties-column>
              <difficulty-type/>
              <comment/>
            </difficulties-column>
          </training>
        </table>
      </non-indigenous-species>
      <bird>
        <table>
          <legal-protection>
            <status-column>
              <status-type/>
              <reference/>
              <comment/>
            </status-column>
            <difficulties-column>
              <difficulty-type/>
              <comment/>
            </difficulties-column>
          </legal-protection>
          <areas>
            <status-column>
              <status-type/>
              <reference/>
              <comment/>
            </status-column>
            <difficulties-column>
              <difficulty-type/>
              <comment/>
            </difficulties-column>
          </areas>
          <programmes>
            <status-column>
              <status-type/>
              <reference/>
              <comment/>
            </status-column>
            <difficulties-column>
              <difficulty-type/>
              <comment/>
            </difficulties-column>
          </programmes>
          <action>
            <status-column>
              <status-type/>
              <reference/>
              <comment/>
            </status-column>
            <difficulties-column>
              <difficulty-type/>
              <comment/>
            </difficulties-column>
          </action>
        </table>
      </bird>
      <cetaceans>
        <table>
          <action>
            <status-column>
              <status-type/>
              <reference/>
              <comment/>
            </status-column>
            <difficulties-column>
              <difficulty-type/>
              <comment/>
            </difficulties-column>
          </action>
          <studies>
            <status-column>
              <status-type/>
              <reference/>
              <comment/>
            </status-column>
            <difficulties-column>
              <difficulty-type/>
              <comment/>
            </difficulties-column>
          </studies>
          <monitoring>
            <status-column>
              <status-type/>
              <reference/>
              <comment/>
            </status-column>
            <difficulties-column>
              <difficulty-type/>
              <comment/>
            </difficulties-column>
          </monitoring>
          <areas>
            <status-column>
              <status-type/>
              <reference/>
              <comment/>
            </status-column>
            <difficulties-column>
              <difficulty-type/>
              <comment/>
            </difficulties-column>
          </areas>
        </table>
      </cetaceans>
      <marine-vegetation>
        <table>
          <protection>
            <status-column>
              <status-type/>
              <reference/>
              <comment/>
            </status-column>
            <difficulties-column>
              <difficulty-type/>
              <comment/>
            </difficulties-column>
          </protection>
          <impact>
            <status-column>
              <status-type/>
              <reference/>
              <comment/>
            </status-column>
            <difficulties-column>
              <difficulty-type/>
              <comment/>
            </difficulties-column>
          </impact>
          <areas>
            <status-column>
              <status-type/>
              <reference/>
              <comment/>
            </status-column>
            <difficulties-column>
              <difficulty-type/>
              <comment/>
            </difficulties-column>
          </areas>
          <monuments>
            <status-column>
              <status-type/>
              <reference/>
              <comment/>
            </status-column>
            <difficulties-column>
              <difficulty-type/>
              <comment/>
            </difficulties-column>
          </monuments>
          <meadows>
            <status-column>
              <status-type/>
              <reference/>
              <comment/>
            </status-column>
            <difficulties-column>
              <difficulty-type/>
              <comment/>
            </difficulties-column>
          </meadows>
          <organogenic>
            <status-column>
              <status-type/>
              <reference/>
              <comment/>
            </status-column>
            <difficulties-column>
              <difficulty-type/>
              <comment/>
            </difficulties-column>
          </organogenic>
          <conservation>
            <status-column>
              <status-type/>
              <reference/>
              <comment/>
            </status-column>
            <difficulties-column>
              <difficulty-type/>
              <comment/>
            </difficulties-column>
          </conservation>
          <plan>
            <status-column>
              <status-type/>
              <reference/>
              <comment/>
            </status-column>
            <difficulties-column>
              <difficulty-type/>
              <comment/>
            </difficulties-column>
          </plan>
        </table>
      </marine-vegetation>
      <monk-seal>
        <table>
          <status>
            <status-column>
              <status-type/>
              <reference/>
              <comment/>
            </status-column>
            <difficulties-column>
              <difficulty-type/>
              <comment/>
            </difficulties-column>
          </status>
          <dynamite>
            <status-column>
              <status-type/>
              <reference/>
              <comment/>
            </status-column>
            <difficulties-column>
              <difficulty-type/>
              <comment/>
            </difficulties-column>
          </dynamite>
          <isolation>
            <status-column>
              <status-type/>
              <reference/>
              <comment/>
            </status-column>
            <difficulties-column>
              <difficulty-type/>
              <comment/>
            </difficulties-column>
          </isolation>
          <spas>
            <status-column>
              <status-type/>
              <reference/>
              <comment/>
            </status-column>
            <difficulties-column>
              <difficulty-type/>
              <comment/>
            </difficulties-column>
          </spas>
          <caves>
            <status-column>
              <status-type/>
              <reference/>
              <comment/>
            </status-column>
            <difficulties-column>
              <difficulty-type/>
              <comment/>
            </difficulties-column>
          </caves>
          <collection>
            <status-column>
              <status-type/>
              <reference/>
              <comment/>
            </status-column>
            <difficulties-column>
              <difficulty-type/>
              <comment/>
            </difficulties-column>
          </collection>
          <awareness>
            <status-column>
              <status-type/>
              <reference/>
              <comment/>
            </status-column>
            <difficulties-column>
              <difficulty-type/>
              <comment/>
            </difficulties-column>
          </awareness>
          <conservation>
            <status-column>
              <status-type/>
              <reference/>
              <comment/>
            </status-column>
            <difficulties-column>
              <difficulty-type/>
              <comment/>
            </difficulties-column>
          </conservation>
        </table>
      </monk-seal>
      <turtles>
        <table>
          <law>
            <status-column>
              <status-type/>
              <reference/>
              <comment/>
            </status-column>
            <difficulties-column>
              <difficulty-type/>
              <comment/>
            </difficulties-column>
          </law>
          <incidental-catch>
            <status-column>
              <status-type/>
              <reference/>
              <comment/>
            </status-column>
            <difficulties-column>
              <difficulty-type/>
              <comment/>
            </difficulties-column>
          </incidental-catch>
          <rescue>
            <status-column>
              <status-type/>
              <reference/>
              <comment/>
            </status-column>
            <difficulties-column>
              <difficulty-type/>
              <comment/>
            </difficulties-column>
          </rescue>
          <spas>
            <status-column>
              <status-type/>
              <reference/>
              <comment/>
            </status-column>
            <difficulties-column>
              <difficulty-type/>
              <comment/>
            </difficulties-column>
          </spas>
          <beaches>
            <status-column>
              <status-type/>
              <reference/>
              <comment/>
            </status-column>
            <difficulties-column>
              <difficulty-type/>
              <comment/>
            </difficulties-column>
          </beaches>
          <tagging>
            <status-column>
              <status-type/>
              <reference/>
              <comment/>
            </status-column>
            <difficulties-column>
              <difficulty-type/>
              <comment/>
            </difficulties-column>
          </tagging>
          <awareness>
            <status-column>
              <status-type/>
              <reference/>
              <comment/>
            </status-column>
            <difficulties-column>
              <difficulty-type/>
              <comment/>
            </difficulties-column>
          </awareness>
          <conservation>
            <status-column>
              <status-type/>
              <reference/>
              <comment/>
            </status-column>
            <difficulties-column>
              <difficulty-type/>
              <comment/>
            </difficulties-column>
          </conservation>
        </table>
      </turtles>
    </effectiveness>
  </report>
</spa-biodiversity>
"""
