# Script (Python) "EnvelopeDeleteAllFeedback"
# bind container=container
# bind context=context
# bind namespace=
# bind script=script
# bind subpath=traverse_subpath
##parameters=workitem_id, REQUEST
# title=Deletes all feedback not generated by conversions - including manual
##
context.getMySelf().manage_delObjects([x for x in context.getMySelf(
).objectIds('Report Feedback') if not x.startswith('conversion_log')])
