## Script (Python) "EnvelopeAddReceiptConfirmation"
##bind container=container
##bind context=context
##bind namespace=
##bind script=script
##bind subpath=traverse_subpath
##parameters=workitem_id, REQUEST
##title=Add a generic confirmation of receipt
##
from DateTime import DateTime

def getActorDraft():
    latestDraftWokitem = [wi for wi in context.getListOfWorkitems() if wi.activity_id == 'Draft'][-1]
    return latestDraftWokitem.actor

list_of_obligations = []
the_envelope = context.getMySelf()

for obl in list(the_envelope.dataflow_uris):
    list_of_obligations.append("""<strong>%s</strong> (<a href="%s">%s</a>)""" % (the_envelope.dataflow_lookup(obl)['TITLE'], obl, obl))

obligations_para = "<br/>\n".join(list_of_obligations)

l_ret = """
<p>
European Environment Agency<br />
Kongens Nytorv 6<br />
DK 1050 Copenhagen K
</p>

<br />
<p><strong>To Whom It May Concern</strong></p>

<br />
<p>This is a confirmation of receipt for national data submissions under the European Reporting Obligation</p>

<p>%s</p>

<p>
The following delivery has been submitted for <strong>%s</strong> to the Reportnet Central Data Repository (CDR) and was made available on <strong>%s</strong>.
</p>

<table>
<tr><td>Envelope:</td><td>%s</td></tr>
<tr><td>Location:</td><td><a href="%s">%s</a></td></tr>
</table>

<p>List of files:</p>

<ol>""" % (obligations_para, the_envelope.getCountryName(), DateTime().strftime('%d %B %Y'), the_envelope.title_or_id(), the_envelope.absolute_url(), the_envelope.absolute_url())

documents_list = the_envelope.objectValues(['Report Document', 'Report Hyperlink'])
documents_list.sort(key=lambda ob: ob.getId().lower())
for f in documents_list:
    l_ret += '<li>%s</li>' % (f.id)
    if f.meta_type == 'Report Document':
        zip_files = the_envelope.getZipInfo(f)
        if zip_files:
            l_ret += '<div class="zip_content">'
            l_ret += '<em>files contained inside the ' + f.title_or_id() + ' archive:</em>'
            l_ret += '<ul>'
            for file in zip_files:
                l_ret += '<li>%s</li>' % file
            l_ret += '</ul>'
            l_ret += '</div>'
l_ret += """
</ol>

<p>
The above-mentioned files were submitted by user: %s (%s)
</p>

<p><em>
This confirmation is electronically generated by the Reportnet system and therefore not signed.
</em></p>
""" % (the_envelope.getLDAPUserCanonicalName(the_envelope.getLDAPUser(getActorDraft())), getActorDraft())

context.getMySelf().manage_addFeedback(title="Confirmation of receipt", feedbacktext=l_ret, automatic=1, content_type='text/html')
context.getMySelf().completeWorkitem(workitem_id)
