## Script (Python) "form10"
##bind container=container
##bind context=context
##bind namespace=
##bind script=script
##bind subpath=traverse_subpath
##parameters=languages
##title=
##
return '''<?xml version="1.0" encoding="UTF-8"?>
<form10 xsi:noNamespaceSchemaLocation="http://air-climate.eionet.europa.eu/schemas/AirQualityQuestionnaire/AirQualityQuestionnaire-form10.xsd"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xml:lang="%s">
	<form10a>
		<form10a-row>
			<zone-code/>
			<uat-lat-24>
				<uat/>
				<uat-lat/>
				<lat/>
			</uat-lat-24>
			<uat-lat-w>
				<uat/>
				<uat-lat/>
				<lat/>
			</uat-lat-w>
			<sa>false</sa>
		</form10a-row>
	</form10a>
	<form10b>
		<form10b-row>
			<zone-code/>
			<uat-lat-1hr>
				<uat/>
				<uat-lat/>
				<lat/>
			</uat-lat-1hr>
			<uat-lat-y>
				<uat/>
				<uat-lat/>
				<lat/>
			</uat-lat-y>
			<uat-lat-veg>
				<uat/>
				<uat-lat/>
				<lat/>
			</uat-lat-veg>
			<sa>false</sa>
		</form10b-row>
	</form10b>
	<form10c>
		<form10c-row>
			<zone-code/>
			<uat-lat-24>
				<uat/>
				<uat-lat/>
				<lat/>
			</uat-lat-24>
			<uat-lat-y>
				<uat/>
				<uat-lat/>
				<lat/>
			</uat-lat-y>
			<sa>false</sa>
		</form10c-row>
	</form10c>
	<form10d>
		<form10d-row>
			<zone-code/>
			<uat-and-lat>
				<uat/>
				<uat-lat/>
				<lat/>
			</uat-and-lat>
			<sa>false</sa>
		</form10d-row>
	</form10d>
	<form10e>
		<form10e-row>
			<zone-code/>
			<uat-and-lat>
				<uat/>
				<uat-lat/>
				<lat/>
			</uat-and-lat>
			<sa>false</sa>
		</form10e-row>
	</form10e>
	<form10f>
		<form10f-row>
			<zone-code/>
			<uat-and-lat>
				<uat/>
				<uat-lat/>
				<lat/>
			</uat-and-lat>
			<sa>false</sa>
		</form10f-row>
	</form10f>
	<form10g>
		<form10g-row>
			<zone-code/>
			<sa>false</sa>
		</form10g-row>
	</form10g>
	<form10h>
		<form10h-row>
			<zone-code/>
			<uat-and-lat>
				<uat/>
				<uat-lat/>
				<lat/>
			</uat-and-lat>
			<sa>false</sa>
		</form10h-row>
	</form10h>
	<form10i>
		<form10i-row>
			<zone-code/>
			<uat-and-lat>
				<uat/>
				<uat-lat/>
				<lat/>
			</uat-and-lat>
			<sa>false</sa>
		</form10i-row>
	</form10i>
	<form10j>
		<form10j-row>
			<zone-code/>
			<uat-and-lat>
				<uat/>
				<uat-lat/>
				<lat/>
			</uat-and-lat>
			<sa>false</sa>
		</form10j-row>
	</form10j>
	<form10k>
		<form10k-row>
			<zone-code/>
			<uat-and-lat>
				<uat/>
				<uat-lat/>
				<lat/>
			</uat-and-lat>
			<sa>false</sa>
		</form10k-row>
	</form10k>
	<form-comments/>
</form10>''' % languages
