return '''<?xml version="1.0" encoding="UTF-8"?>
<form5  xsi:noNamespaceSchemaLocation="http://air-climate.eionet.europa.eu/schemas/AirQualityQuestionnaire/AirQualityQuestionnaire-form5.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:xi="http://www.w3.org/2001/XInclude"
	xml:lang="%s">
	<form5a>
		<form5a-row>
			<eoi-station-code/>
			<local-station-code/>
			<ozone-zone-code/>
			<elements>
				<ethane/>
				<ethylene/>
				<acetylene/>
				<propane/>
				<propene/>
				<n-butane/>
				<i-butane/>
				<butene-1/>
				<trans-2butene/>
				<cis-2butene/>
				<butadiene13/>
				<n-pentane/>
				<i-pentane/>
				<pentene-1/>
				<pentene-2/>
				<isoprene/>
				<n-hexane/>
				<i-hexane/>
				<n-heptane/>
				<n-octane/>
				<i-octane/>
				<benzene/>
				<toluene/>
				<ethyl-benzene/>
				<mp-xylene/>
				<o-xylene/>
				<trimeth-benzene-124/>
				<trimeth-benzene-123/>
				<trimeth-benzene-135/>
				<formaldehyde/>
				<total-non-methane-hydrocarbons></total-non-methane-hydrocarbons>
			</elements>
		</form5a-row>
	</form5a>
	<form5b>
		<form5b-row>
			<eoi-station-code/>
			<local-station-code/>
			<zone-code/>
			<pah-elements-form5>
				<element>
					<name>benzo(a)anthracene</name>
					<sampling/>
					<analysis/>
				</element>
				<element>
					<name>benzo(b)fluoranthene</name>
					<sampling/>
					<analysis/>
				</element>
				<element>
					<name>benzo(j)fluoranthene</name>
					<sampling/>
					<analysis/>
				</element>
				<element>
					<name>benzo(k)fluoranthene</name>
					<sampling/>
					<analysis/>
				</element>
				<element>
					<name>indeno(1,2,3-cd)pyrene</name>
					<sampling/>
					<analysis/>
				</element>
				<element>
					<name>dibenz(a,h)anthracene</name>
					<sampling/>
					<analysis/>
				</element>
			</pah-elements-form5>
		</form5b-row>
	</form5b>
	<form5c>
		<form5c-row>
			<eoi-station-code/>
			<local-station-code/>
			<zone-code/>
			<monitoring-in-air-deposition/>
			<pah-elements-form5>
				<element>
					<name>Arsenic</name>
					<sampling/>
					<analysis/>
				</element>
				<element>
					<name>Cadmium</name>
					<sampling/>
					<analysis/>
				</element>
				<element>
					<name>Nickel</name>
					<sampling/>
					<analysis/>
				</element>
				<element>
					<name>benzo(a)pyrene</name>
					<sampling/>
					<analysis/>
				</element>
				<element>
					<name>benzo(a)anthracene</name>
					<sampling/>
					<analysis/>
				</element>
				<element>
					<name>benzo(b)fluoranthene,</name>
					<sampling/>
					<analysis/>
				</element>
				<element>
					<name>benzo(j)fluoranthene,</name>
					<sampling/>
					<analysis/>
				</element>
				<element>
					<name>benzo(k)fluoranthene</name>
					<sampling/>
					<analysis/>
				</element>
				<element>
					<name>indeno(1,2,3-cd)pyrene</name>
					<sampling/>
					<analysis/>
				</element>
				<element>
					<name>dibenz(a,h)anthracene</name>
					<sampling/>
					<analysis/>
				</element>
				<element>
					<name>total (gaseous) Mercury</name>
					<sampling/>
					<analysis/>
				</element>
				<element>
					<name>particulate divalent mercury</name>
					<sampling/>
					<analysis/>
				</element>
				<element>
					<name>gaseous divalent mercury</name>
					<sampling/>
					<analysis/>
				</element>
			</pah-elements-form5>
		</form5c-row>
	</form5c>
	<form-comments/>
</form5>''' % languages
