## Script (Python) "form11"
##bind container=container
##bind context=context
##bind namespace=
##bind script=script
##bind subpath=traverse_subpath
##parameters=languages
##title=
##
return '''<?xml version="1.0" encoding="UTF-8"?>
<form11 xsi:noNamespaceSchemaLocation="http://air-climate.eionet.europa.eu/schemas/AirQualityQuestionnaire/AirQualityQuestionnaire-form11.xsd"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xml:lang="%s">
	<form11a>
		<form11a-row>
			<zone-code/>
			<eoi-station-code></eoi-station-code>
			<month></month>
			<day-of-month></day-of-month>
			<hour></hour>
			<level></level>
			<reason-code></reason-code>
		</form11a-row>
	</form11a>
	<form11b>
		<form11b-row>
			<zone-code/>
			<eoi-station-code></eoi-station-code>
			<month></month>
			<day-of-month></day-of-month>
			<level></level>
			<reason-code></reason-code>
		</form11b-row>
	</form11b>
	<form11c>
		<form11c-row>
			<zone-code/>
			<eoi-station-code></eoi-station-code>
			<level></level>
			<reason-code></reason-code>
		</form11c-row>
	</form11c>
	<form11d>
		<form11d-row>
			<zone-code/>
			<eoi-station-code></eoi-station-code>
			<level></level>
			<reason-code></reason-code>
		</form11d-row>
	</form11d>
	<form11e>
		<form11e-row>
			<zone-code/>
			<eoi-station-code></eoi-station-code>
			<month></month>
			<day-of-month></day-of-month>
			<hour></hour>
			<level></level>
			<reason-code></reason-code>
		</form11e-row>
	</form11e>
	<form11f>
		<form11f-row>
			<zone-code/>
			<eoi-station-code></eoi-station-code>
			<level></level>
			<reason-code></reason-code>
		</form11f-row>
	</form11f>
	<form11g>
		<form11g-row>
			<zone-code/>
			<eoi-station-code></eoi-station-code>
			<level></level>
			<reason-code></reason-code>
		</form11g-row>
	</form11g>
	<form11h>
		<form11h-row>
			<zone-code/>
			<eoi-station-code></eoi-station-code>
			<month></month>
			<day-of-month></day-of-month>
			<level></level>
			<reason-code></reason-code>
		</form11h-row>
	</form11h>
	<form11i>
		<form11i-row>
			<zone-code/>
			<eoi-station-code></eoi-station-code>
			<level></level>
			<reason-code></reason-code>
		</form11i-row>
	</form11i>
	<form11j>
		<form11j-row>
			<zone-code/>
			<eoi-station-code></eoi-station-code>
			<level></level>
			<reason-code></reason-code>
		</form11j-row>
	</form11j>
	<form11k>
		<form11k-row>
			<zone-code/>
			<eoi-station-code></eoi-station-code>
			<level></level>
			<reason-code></reason-code>
			<article-3></article-3>
		</form11k-row>
	</form11k>
	<form11l>
		<form11l-row>
			<zone-code/>
			<eoi-station-code></eoi-station-code>
			<month></month>
			<day-of-month></day-of-month>
			<level></level>
			<reason-code></reason-code>
		</form11l-row>
	</form11l>
	<form-comments/>
</form11>''' % languages
