# Script (Python) "form19"
# bind container=container
# bind context=context
# bind namespace=
# bind script=script
# bind subpath=traverse_subpath
# parameters=languages
# title=
##
return '''<?xml version="1.0" encoding="UTF-8"?>
<form19 xsi:noNamespaceSchemaLocation="http://air-climate.eionet.europa.eu/schemas/AirQualityQuestionnaire/AirQualityQuestionnaire-form19.xsd"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xml:lang="%s">
	<form19a>
		<form19a-row>
			<zone-code></zone-code>
			<above-lv-heal-1hr>
				<area>
					<km2></km2>
					<method></method>
				</area>
				<population-exposed>
					<number></number>
					<method></method>
				</population-exposed>
			</above-lv-heal-1hr>
			<above-lv-heal-24hr>
				<area>
					<km2></km2>
					<method></method>
				</area>
				<population-exposed>
					<number></number>
					<method></method>
				</population-exposed>
			</above-lv-heal-24hr>
			<above-lv-eco-y>
				<area>
					<km2></km2>
					<method></method>
				</area>
				<eco-area-exposed>
					<km2></km2>
					<method></method>
				</eco-area-exposed>
			</above-lv-eco-y>
			<above-lv-eco-w>
				<area>
					<km2></km2>
					<method></method>
				</area>
				<eco-area-exposed>
					<km2></km2>
					<method></method>
				</eco-area-exposed>
			</above-lv-eco-w>
		</form19a-row>
	</form19a>
	<form19b>
		<form19b-row>
			<zone-code></zone-code>
			<lv-health-1hr>
				<area>
					<km2></km2>
					<method></method>
				</area>
				<road-length>
					<km></km>
					<method></method>
				</road-length>
				<population-exposed>
					<number></number>
					<method></method>
				</population-exposed>
			</lv-health-1hr>
			<lv-health-y>
				<area>
					<km2></km2>
					<method></method>
				</area>
				<road-length>
					<km></km>
					<method></method>
				</road-length>
				<population-exposed>
					<number></number>
					<method></method>
				</population-exposed>
			</lv-health-y>
			<lv-health-veg>
				<area>
					<km2></km2>
					<method></method>
				</area>
				<veg-area-exposed>
					<km2></km2>
					<method></method>
				</veg-area-exposed>
			</lv-health-veg>
		</form19b-row>
	</form19b>
	<form19c>
		<form19c1>
			<form19c1-row>
				<zone-code></zone-code>
				<lv-health-24hr>
					<area>
						<km2></km2>
						<method></method>
					</area>
					<road-length>
						<km></km>
						<method></method>
					</road-length>
					<population-exposed>
						<number></number>
						<method></method>
					</population-exposed>
				</lv-health-24hr>
				<lv-health-y>
					<area>
						<km2></km2>
						<method></method>
					</area>
					<road-length>
						<km></km>
						<method></method>
					</road-length>
					<population-exposed>
						<number></number>
						<method></method>
					</population-exposed>
				</lv-health-y>
			</form19c1-row>
		</form19c1>
		<form19c2>
			<form19c2-row>
				<zone-code></zone-code>
				<lv-health-24hr>
					<area>
						<km2></km2>
						<method></method>
					</area>
					<road-length>
						<km></km>
						<method></method>
					</road-length>
					<population-exposed>
						<number></number>
						<method></method>
					</population-exposed>
				</lv-health-24hr>
				<lv-health-y>
					<area>
						<km2></km2>
						<method></method>
					</area>
					<road-length>
						<km></km>
						<method></method>
					</road-length>
					<population-exposed>
						<number></number>
						<method></method>
					</population-exposed>
				</lv-health-y>
			</form19c2-row>
		</form19c2>
	</form19c>
	<form19d>
		<form19d-row>
			<zone-code></zone-code>
			<above-lv>
				<area>
					<km2></km2>
					<method></method>
				</area>
				<road-length>
					<km></km>
					<method></method>
				</road-length>
				<population-exposed>
					<number></number>
					<method></method>
				</population-exposed>
			</above-lv>
		</form19d-row>
	</form19d>
	<form19e>
		<form19e-row>
			<zone-code></zone-code>
			<above-lv>
				<area>
					<km2></km2>
					<method></method>
				</area>
				<road-length>
					<km></km>
					<method></method>
				</road-length>
				<population-exposed>
					<number></number>
					<method></method>
				</population-exposed>
			</above-lv>
		</form19e-row>
	</form19e>
	<form19f>
		<form19f-row>
			<zone-code></zone-code>
			<above-lv>
				<area>
					<km2></km2>
					<method></method>
				</area>
				<road-length>
					<km></km>
					<method></method>
				</road-length>
				<population-exposed>
					<number></number>
					<method></method>
				</population-exposed>
			</above-lv>
		</form19f-row>
	</form19f>
	<form19g>
		<form19g-row>
			<zone-code></zone-code>
			<tv-above-health>
				<area>
					<km2></km2>
					<method></method>
				</area>
				<population-exposed>
					<number></number>
					<method></method>
				</population-exposed>
			</tv-above-health>
			<lto-above-health>
				<area>
					<km2></km2>
					<method></method>
				</area>
				<population-exposed>
					<number></number>
					<method></method>
				</population-exposed>
			</lto-above-health>
			<tv-above-eco>
				<area>
					<km2></km2>
					<method></method>
				</area>
				<eco-area-exposed>
					<km2></km2>
					<method></method>
				</eco-area-exposed>
			</tv-above-eco>
			<lto-above-eco>
				<area>
					<km2></km2>
					<method></method>
				</area>
				<eco-area-exposed>
					<km2></km2>
					<method></method>
				</eco-area-exposed>
			</lto-above-eco>
		</form19g-row>
	</form19g>
	<form19h>
		<form19h-row>
			<zone-code></zone-code>
			<tv-above-health>
				<area>
					<km2></km2>
					<method></method>
				</area>
				<population-exposed>
					<number></number>
					<method></method>
				</population-exposed>
			</tv-above-health>
		</form19h-row>
	</form19h>
	<form19i>
		<form19i-row>
			<zone-code></zone-code>
			<tv-above-health>
				<area>
					<km2></km2>
					<method></method>
				</area>
				<population-exposed>
					<number></number>
					<method></method>
				</population-exposed>
			</tv-above-health>
		</form19i-row>
	</form19i>
	<form19j>
		<form19j-row>
			<zone-code></zone-code>
			<tv-above-health>
				<area>
					<km2></km2>
					<method></method>
				</area>
				<population-exposed>
					<number></number>
					<method></method>
				</population-exposed>
			</tv-above-health>
		</form19j-row>
	</form19j>
	<form19k>
		<form19k-row>
			<zone-code></zone-code>
			<tv-above-health>
				<area>
					<km2></km2>
					<method></method>
				</area>
				<population-exposed>
					<number></number>
					<method></method>
				</population-exposed>
			</tv-above-health>
		</form19k-row>
	</form19k>
	<form19l>
		<form19l-row>
			<zone-code></zone-code>
			<tv-above>
				<area>
					<km2></km2>
					<method></method>
				</area>
				<road-length>
					<km></km>
					<method></method>
				</road-length>
				<population-exposed>
					<number></number>
					<method></method>
				</population-exposed>
			</tv-above>
		</form19l-row>
	</form19l>
	<form-comments/>
</form19>''' % languages
