# Script (Python) "form25"
# bind container=container
# bind context=context
# bind namespace=
# bind script=script
# bind subpath=traverse_subpath
# parameters=languages
# title=
##
return '''<?xml version="1.0" encoding="UTF-8"?>
<form25 xsi:noNamespaceSchemaLocation="http://air-climate.eionet.europa.eu/schemas/AirQualityQuestionnaire/AirQualityQuestionnaire-form25.xsd"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xml:lang="%s">
	<form25a>
		<has-consulted>true</has-consulted>
	</form25a>
	<form25b>
		<country>
			<code>AT</code>
			<concerned>false</concerned>
			<agenda>false</agenda>
			<minutes>false</minutes>
		</country>
		<country>
			<code>BE</code>
			<concerned>false</concerned>
			<agenda>false</agenda>
			<minutes>false</minutes>
		</country>
		<country>
			<code>CY</code>
			<concerned>false</concerned>
			<agenda>false</agenda>
			<minutes>false</minutes>
		</country>
		<country>
			<code>CZ</code>
			<concerned>false</concerned>
			<agenda>false</agenda>
			<minutes>false</minutes>
		</country>
		<country>
			<code>DE</code>
			<concerned>false</concerned>
			<agenda>false</agenda>
			<minutes>false</minutes>
		</country>
		<country>
			<code>DK</code>
			<concerned>false</concerned>
			<agenda>false</agenda>
			<minutes>false</minutes>
		</country>
		<country>
			<code>EE</code>
			<concerned>false</concerned>
			<agenda>false</agenda>
			<minutes>false</minutes>
		</country>
		<country>
			<code>ES</code>
			<concerned>false</concerned>
			<agenda>false</agenda>
			<minutes>false</minutes>
		</country>
		<country>
			<code>FI</code>
			<concerned>false</concerned>
			<agenda>false</agenda>
			<minutes>false</minutes>
		</country>
		<country>
			<code>FR</code>
			<concerned>false</concerned>
			<agenda>false</agenda>
			<minutes>false</minutes>
		</country>
		<country>
			<code>GR</code>
			<concerned>false</concerned>
			<agenda>false</agenda>
			<minutes>false</minutes>
		</country>
		<country>
			<code>HU</code>
			<concerned>false</concerned>
			<agenda>false</agenda>
			<minutes>false</minutes>
		</country>
		<country>
			<code>IE</code>
			<concerned>false</concerned>
			<agenda>false</agenda>
			<minutes>false</minutes>
		</country>
		<country>
			<code>IT</code>
			<concerned>false</concerned>
			<agenda>false</agenda>
			<minutes>false</minutes>
		</country>
		<country>
			<code>LT</code>
			<concerned>false</concerned>
			<agenda>false</agenda>
			<minutes>false</minutes>
		</country>
		<country>
			<code>LU</code>
			<concerned>false</concerned>
			<agenda>false</agenda>
			<minutes>false</minutes>
		</country>
		<country>
			<code>LV</code>
			<concerned>false</concerned>
			<agenda>false</agenda>
			<minutes>false</minutes>
		</country>
		<country>
			<code>MT</code>
			<concerned>false</concerned>
			<agenda>false</agenda>
			<minutes>false</minutes>
		</country>
		<country>
			<code>NL</code>
			<concerned>false</concerned>
			<agenda>false</agenda>
			<minutes>false</minutes>
		</country>
		<country>
			<code>PL</code>
			<concerned>false</concerned>
			<agenda>false</agenda>
			<minutes>false</minutes>
		</country>
		<country>
			<code>PT</code>
			<concerned>false</concerned>
			<agenda>false</agenda>
			<minutes>false</minutes>
		</country>
		<country>
			<code>SE</code>
			<concerned>false</concerned>
			<agenda>false</agenda>
			<minutes>false</minutes>
		</country>
		<country>
			<code>SK</code>
			<concerned>false</concerned>
			<agenda>false</agenda>
			<minutes>false</minutes>
		</country>
		<country>
			<code>SI</code>
			<concerned>false</concerned>
			<agenda>false</agenda>
			<minutes>false</minutes>
		</country>
		<country>
			<code>UK</code>
			<concerned>false</concerned>
			<agenda>false</agenda>
			<minutes>false</minutes>
		</country>
	</form25b>
	<form-comments/>
</form25>''' % languages
