return {
    'AT': { 'ALP': 1, 'CON': 1, },
    'BE': { 'ATL': 1, 'CON': 1, 'MATL': 1, },
    'CY': { 'MED': 1, 'MMED': 1, },
    'CZ': { 'CON': 1, 'PAN': 1, },
    'DE': { 'ALP': 1, 'ATL': 1, 'CON': 1, 'MATL': 1, 'MBAL': 1, },
    'DK': { 'ATL': 1, 'CON': 1, 'MATL': 1, 'MBAL': 1, },
    'EE': { 'BOR': 1, 'MBAL': 1, },
    'ES': { 'ALP': 1, 'ATL': 1, 'MAC': 1, 'MED': 1, 'MATL': 1, 'MMED': 1, 'MMAC': 1, },
    'FI': { 'ALP': 1, 'BOR': 1, 'MBAL': 1, },
    'FR': { 'ALP': 1, 'ATL': 1, 'CON': 1, 'MED': 1, 'MATL': 1, 'MMED': 1, },
    'GR': { 'MED': 1, 'MMED': 1, },
    'HU': { 'PAN': 1, },
    'IE': { 'ATL': 1, 'MATL': 1, },
    'IT': { 'ALP': 1, 'CON': 1, 'MED': 1, 'MMED': 1, },
    'LT': { 'BOR': 1, 'MBAL': 1, },
    'LU': { 'CON': 1, },
    'LV': { 'BOR': 1, 'MBAL': 1, },
    'MT': { 'MED': 1, 'MMED': 1, },
    'NL': { 'ATL': 1, 'MATL': 1, },
    'PL': { 'ALP': 1, 'CON': 1, 'MBAL': 1, },
    'PT': { 'ATL': 1, 'MAC': 1, 'MED': 1, 'MATL': 1, 'MMAC': 1, },
    'SE': { 'ALP': 1, 'BOR': 1, 'CON': 1, 'MBAL': 1, },
    'SI': { 'ALP': 1, 'CON': 1, 'MMED': 1, },
    'SK': { 'ALP': 1, 'PAN': 1, },
    'UK': { 'ATL': 1, 'MED': 1, 'MATL': 1, 'MMED': 1, },
}
