swagger: '2.0'
info:
  version: 1.0.0
  title: Envelopes
  description: ''
host: 'localhost:8081'
basePath: /api
schemes:
  - http
  - https
produces:
  - application/json
paths:
  /envelopes:
    get:
      tags:
        - envelopes
      parameters:
        - name: isReleased
          in: query
          description: Released(1) or Unreleased(0) envelopes to return
          type: integer
          minimum: 0
          maximum: 1
          enum:
            - 0
            - 1
        - name: url
          in: query
          description: Url of the envelopes or part of to return
          type: string
        - name: countryCode
          in: query
          description: Country code in ISO "ALPHA-2 Code format for envelopes to return
          type: string
          enum:
            - AL
            - DZ
            - AD
            - AM
            - AT
            - AZ
            - BY
            - BE
            - BA
            - BG
            - HR
            - CY
            - CZ
            - DK
            - EG
            - EE
            - EU
            - FI
            - FR
            - GE
            - DE
            - GI
            - GR
            - GL
            - HU
            - IS
            - IE
            - IL
            - IT
            - JO
            - KZ
            - XK
            - KG
            - LV
            - LB
            - LY
            - LI
            - LT
            - LU
            - MK
            - MT
            - MD
            - MC
            - ME
            - MA
            - NL
            - NO
            - PS
            - PL
            - PT
            - RO
            - RU
            - SM
            - RS
            - SK
            - SI
            - ES
            - SE
            - CH
            - SY
            - TJ
            - TN
            - TR
            - TM
            - UA
            - GB
            - UZ
            - VA
        - name: reportingDate
          in: query
          description: Return envelopes with this reporting date. format.
          type: string
          format: date
        - name: reportingDateStart
          in: query
          description: >-
            Return envelopes that have a reporting date in range of
            reportingDateStart and reportingDateEnd or today if reportingDateEnd
            is missing.
          type: string
          format: date
        - name: reportingDateEnd
          in: query
          description: >-
            Return envelopes that have a reporting date in range of
            reportingDateStart and reportingDateEnd. If reportingDateStart is
            missing, all envelopes with reporting date <= reportingDateEnd will
            be returned.
          type: string
          format: date
        - name: obligations
          in: query
          description: Return envelopes with one of the following obligations
          type: array
          items:
            type: integer
          collectionFormat: csv
        - name: periodDescription
          in: query
          description: Return envelopes with specified periodDescription
          type: string
          enum:
            - Whole Year
            - First Half
            - Second Half
            - First Quarter
            - Second Quarter
            - Third Quarter
            - Fourth Quarter
            - January
            - February
            - March
            - April
            - May
            - June
            - July
            - August
            - September
            - October
            - November
            - December
        - name: modifiedDate
          in: query
          description: Return envelopes with specified modifiedDate. date format.
          type: string
          format: date
        - name: modifiedDateStart
          in: query
          description: >-
            Return envelopes that have a modified date in range of
            modifiedDateStart and modifiedDateEnd or today if modifiedDateEnd is
            missing.
          type: string
          format: date
        - name: modifiedDateEnd
          in: query
          description: >-
            Return envelopes that have a modified date in range of
            modifiedDateStart and modifiedDateEnd. If modifiedDateStart is
            missing, all envelopes with modified date <= modifiedDateEnd will be
            returned.
          type: string
          format: date
        - name: status
          in: query
          description: Return envelopes that have the following status
          type: string
        - name: statusDate
          in: query
          type: string
          format: date
          description: Return envelopes that have a status with the following statusDate.
        - name: fields
          in: query
          description: Return envelopes with only the fields specified
          type: array
          items:
            type: string
            enum:
              - files
              - url
              - title
              - description
              - countryCode
              - isReleased
              - reportingDate
              - modifiedDate
              - periodStartYear
              - periodEndYear
              - periodDescription
              - obligations
              - isBlockedByQCError
              - status
              - statusDate
              - creator
              - hasUnknownQC
              - history
          collectionFormat: csv
      responses:
        '200':
          description: List released or unreleased envelopes
          schema:
            type: object
            properties:
              envelopes:
                type: array
                items:
                  $ref: '#/definitions/Envelope'
              errors:
                type: array
                items:
                  $ref: '#/definitions/Error'
          examples:
            'application/json':
              errors:
                - title: Error title
                  description: This is a generic error description
              envelopes:
                - files:
                    - title: My Envelope file
                      archived_files:
                        - File1.xml
                        - File2.xml
                      contentType: application/xml
                      uploadDate: 2013-04-12T23:20:50.52Z
                      url: http://foo/bar/my_envelope/my_envelope_file.xml
                      schemaURL: http://foo/bar/schema.xsd
                  periodEndYear: 2014
                  status: Release
                  countryCode: RO
                  statusDate: 2013-04-13T01:20:50.53Z
                  obligations:
                    - '701'
                  isBlockedByQCError: 0
                  url: http://foo/bar/my_envelope
                  modifiedDate: 2013-04-13T01:20:50.53Z
                  creator: foo
                  history:
                    - id: 0
                      title: Release
                      activity_id: Release
                      activity_status: complete
                      blocker: false
                      modified: 2013-04-13T01:20:50.53Z
                  isReleased: 1
                  title: My Envelope
                  reportingDate: 2013-04-13T01:20:50.53Z
                  periodStartYear: 2013
                  description: A description for my envelope
                  periodDescription: Whole Year
definitions:
  Envelope:
    type: object
    properties:
      title:
        type: string
        description: The envelope's title.
      description:
        type: string
        description: The envelope's description.
      obligations:
        type: array
        description: The obligations for which the envelope has been created.
        items:
          type: integer
      periodStartYear:
        description: >-
          The starting year of the period for which the envelope has been
          created.
        type: string
      periodEndYear:
        type: string
        description: The ending year of the period for which the envelope has been created.
      countryCode:
        type: string
        description: The envelope's country code (ISO Alpha-2).
      reportingDate:
        type: string
        description: The envelope's reporting date.
        format: dateTime
      url:
        type: string
        description: The envelope's URL.
      modifiedDate:
        type: string
        description: The envelope's modification date.
        format: dateTime
      periodDescription:
        $ref: '#/definitions/PeriodDescription'
      isReleased:
        type: integer
        description: The envelope's release status
        enum:
          - 0
          - 1
      isBlockedByQCError:
        type: integer
        description: Is the envelope blocked by a QC Error.
        enum:
          - 0
          - 1
      status:
        type: string
        description: The workflow status of the envelope.
      statusDate:
        type: string
        format: dateTime
        description: The date the workflow status has been set.
      creator:
        type: string
        description: The envelope's creator.
      files:
        type: array
        description: The list of files attached to the envelope.
        items:
          $ref: '#/definitions/File'
      history:
        type: array
        description: The workflow history of the envelope.
        items:
          $ref: '#/definitions/History'
  File:
    type: object
    properties:
      contentType:
        type: string
        description: The file's content type.
      title:
        type: string
        description: The file's title.
      url:
        type: string
        description: The file's URL.
      uploadDate:
        type: string
        description: The file's upload date.
        format: dateTime
      schemaURL:
        type: string
        description: The URL of the file's schema.
      archived_files:
        type: array
        description: >-
          The list of files that have been archived. Available only if there is
          an archive attached to the envelope and if it can be opened.
        items:
          type: string
  History:
    type: object
    properties:
      activity_id:
        type: string
        description: The id of the activity/workflow.
      activity_status:
        type: string
        description: The status of the activity/workflow.
      blocker:
        type: boolean
        description: The blocker status of the activity/workflow.
      title:
        type: string
        description: The title of the activity/workflow.
      modified:
        type: string
        format: dateTime
        description: The modification date of the activity/workflow.
      id:
        type: string
        description: The id of the activity/workflow.
  Error:
    type: object
    properties:
      title:
        type: string
        description: The error's title.
      description:
        type: string
        description: The error's description
  PeriodDescription:
    type: string
    description: The envelope's reporting period description.
    enum:
      - Whole Year
      - First Half
      - Second Half
      - First Quarter
      - Second Quarter
      - Third Quarter
      - Fourth Quarter
      - January
      - February
      - March
      - April
      - May
      - June
      - July
      - August
      - September
      - October
      - November
      - December
