# flake8: noqa
# Script (Python) "AddGGCoverLetter"
# bind container=container
# bind context=context
# bind namespace=
# bind script=script
# bind subpath=traverse_subpath
# parameters=
# title=Adds a cover letter to the envelopes for greenhouse gases that already completed the process
##
from DateTime import DateTime

dfs = ''
for x in context.dataflow_uris:
    dfs += context.dataflow_lookup(x)['TITLE'] + ' (' + \
        context.dataflow_lookup(x)['details_url'] + ')<br />'

for x in context.objectValues('Workitem'):
    if x.activity_id == 'Draft':
        luzr = x.actor
ldapusername = context.getLDAPUserCanonicalName(context.getLDAPUser(luzr))
if not ldapusername:
    ldapusername = luzr

l_ret = """
<p>
European Environment Agency<br />
Kongens Nytorv 6<br />
DK 1050 Copenhagen K
</p>

<p><strong>To Whom It May Concern:</strong></p>

<p>
	This is a confirmation of receipt for national data submissions under the European Reporting Obligation
</p>

<p>
	Greenhouse gas emission inventories (Greenhouse gas monitoring mechanism (Council Decision 280/2004/EC) (<a href="http://rod.eionet.europa.eu/obligations/384">http://rod.eionet.europa.eu/obligations/384</a>)
</p>

<p>
	The following delivery has been submitted for %s to the Reportnet Central Data Repository (CDR) and was finalized on %s.
</p>

<table>
	<tr>
		<th>Envelope:</th>
		<td>%s</td>
	</tr>
	<tr>
		<th>Location:</th>
		<td>%s</td>
	</tr>
</table>
<p>
List of files:
</p>

<ol>""" % (context.getCountryName(), context.reportingdate.strftime('%d %B %Y'), context.title_or_id(), context.absolute_url())

documents_list = context.objectValues(['Report Document', 'Report Hyperlink'])
documents_list.sort(key=lambda ob: ob.getId().lower())
for f in documents_list:
    l_ret += '<li>%s (<a href="%s">%s</a>)</li>' % (f.title_or_id(),
                                                    f.absolute_url(), f.absolute_url())

l_ret += """
</ol>

<p>
The above-mentioned files were submitted by user: <em>%s</em>
</p>

<p><em>
This confirmation letter is electronically generated by the Reportnet system and therefore not signed. 
</em></p>

<p>
	Please note: Member States are requested to notify the Commission (DG ENV Climate Change Unit) of all GHG data submissions uploaded to CDR: <a mailto="erasmia.kitou@ec.europa.eu">erasmia.kitou@ec.europa.eu</a>
</p>
""" % (ldapusername)

context.manage_delObjects(context.objectIds('Report Feedback'))
context.manage_addFeedback(title="Receipt of delivery for Greenhouse gas inventories",
                           feedbacktext=l_ret, automatic=1, content_type='text/html')
