# -*- coding: utf-8 -*-

return [('BE', 'National level', 'BE'), ('FR', 'National level', 'FR'), ('BG', 'National level', 'BG'), ('DK', 'National level', 'DK'), ('DE', 'National level', 'DE'), ('HU', 'National level', 'HU'), ('FI', 'National level', 'FI'), ('NL', 'National level', 'NL'), ('PT', 'National level', 'PT'), ('NO', 'National level', 'NO'), ('LV', 'National level', 'LV'), ('LT', 'National level', 'LT'), ('LU', 'National level', 'LU'), ('RO', 'National level', 'RO'), ('PL', 'National level', 'PL'), ('CH', 'National level', 'CH'), ('GR', 'National level', 'GR'), ('EE', 'National level', 'EE'), ('IT', 'National level', 'IT'), ('CZ', 'National level', 'CZ'), ('CY', 'National level', 'CY'), ('AT', 'National level', 'AT'), ('IE', 'National level', 'IE'), ('ES', 'National level', 'ES'), ('SK', 'National level', 'SK'), ('MT', 'National level', 'MT'), ('SI', 'National level', 'SI'), ('SE', 'National level', 'SE'), ('GB', 'National level', 'GB')]

return [
("AT", "Danube", "AT1000"),
("AT", "Elbe", "AT5000"),  
("AT", "Rhine", "AT2000"), 
("BE", "Meuse", "BEMaas_VL"),
("BE", "Meuse", "BE_Meuse_RW"),
("BE", "Rhine", "BE_Rhin_RW"), 
("BE", "Scheldt", "BE_Escaut_RW"),
("BE", "Scheldt (Brussels Area)", "BE_Escaut_BR"),
("BE", "Scheldt in Flanders", "BESchelde_VL"),    
("BE", "Seine", "BE_Seine_RW"),                   
("BG", "Black Sea Basin District", "BG2000"),     
("BG", "Danube Region Basin District", "BG1000"), 
("BG", "East Aegean Region Basin District", "BG3000"),
("BG", "West Aegean Region Basin District", "BG4000"),
("CH", "Adige", "CH90"),                              
("CH", "Danube", "CH80"),                             
("CH", "Po", "CH60"),                                 
("CH", "Rhine", "CH10"),                              
("CH", "Rhone", "CH50"),                              
("CY", "Cyprus", "CY001"),                            
("CZ", "Danube", "CZ_RB_1000"),                       
("CZ", "Elbe", "CZ_RB_5000"),                         
("CZ", "Oder", "CZ_RB_6000"),                         
("DE", "Danube", "DE1000"),                           
("DE", "Eider", "DE9500"),                            
("DE", "Elbe", "DE5000"),                             
("DE", "Ems", "DE3000"),                              
("DE", "Meuse", "DE7000"),                            
("DE", "Odra", "DE6000"),                             
("DE", "Rhine", "DE2000"),                            
("DE", "Schlei/Trave", "DE9610"),                     
("DE", "Warnow/Peene", "DE9650"),                     
("DE", "Weser", "DE4000"),                            
("DK", "Bornholm", "DK3"),                            
("DK", "Jutland and Funen", "DK1"),                   
("DK", "Vidaa-Krusaa", "DK4"),                        
("DK", "Zealand", "DK2"),                             
("EE", "East Estonia", "EE2"),                        
("EE", "Gauja", "EE3"),                               
("EE", "West Estonia", "EE1"),                        
("ES", "Andalusia Atlantic Basins", "ES062"),         
("ES", "Andalusia Mediterranean Basins", "ES060"),    
("ES", "Balearic Islands", "ES110"),                  
("ES", "Basque County internal basins", "ES015"),     
("ES", "Ceuta", "ES150"),                             
("ES", "Duero", "ES020"),                             
("ES", "Ebro", "ES091"),                              
("ES", "El Hierro", "ES127"),                         
("ES", "Fuerteventura", "ES122"),                     
("ES", "Galician Coast", "ES014"),                    
("ES", "Gran Canaria", "ES120"),                      
("ES", "Guadalquivir", "ES050"),                      
("ES", "Guadiana", "ES040"),                          
("ES", "Internal Basins of Catalonia", "ES100"),      
("ES", "Jucar", "ES080"),                             
("ES", "La Gomera", "ES126"),                         
("ES", "Lanzarote", "ES123"),                         
("ES", "La Palma", "ES125"),                          
("ES", "Melilla", "ES160"),                           
("ES", "Minho", "ES010"),                             
("ES", "Northern Spain", "ES016"),                    
("ES", "Segura", "ES070"),                            
("ES", "Tagus", "ES030"),                             
("ES", "Tenerife", "ES124"),                          
("FI", "Aland islands", "FIWDA"),                     
("FI", "Kemijoki", "FIVHA5"),                         
("FI", "Kokemäenjoki-Archipelago Sea-Bothnian Sea", "FIVHA3"),
("FI", "Kymijoki-Gulf of Finland", "FIVHA2"),                 
("FI", "Oulujoki-Iijoki", "FIVHA4"),                          
("FI", "Teno-, Näätämö- and Paatsjoki (Finnish part)", "FIVHA7"),
("FI", "Tornionjoki (Finnish part)", "FIVHA6"),                  
("FI", "Vuoksi", "FIVHA1"),                                      
("FR", "Adour, Garonne, Dordogne, Charente and coastal waters of aquitania", "FRF"),
("FR", "Corsica", "FRE"),                                                           
("FR", "Guadeloupe", "FRI"),                                                        
("FR", "Guyana (French)", "FRK"),                                                   
("FR", "Loire, Brittany and Vendee coastal waters", "FRG"),                         
("FR", "Martinique", "FRJ"),                                                        
("FR", "Meuse", "FRB1"),                                                            
("FR", "Reunion Island", "FRL"),                                                    
("FR", "Rhine", "FRC"),                                                             
("FR", "Rhone and Coastal Mediterranean", "FRD"),                                   
("FR", "Sambre", "FRB2"),                                                           
("FR", "Scheldt, Somme and coastal waters of the Channel and the North Sea", "FRA"),
("FR", "Seine and Normandy coastal waters", "FRH"),                                 
("GR", "Aegean Islands", "GR14"),                                                   
("GR", "Attica", "GR06"),                                                           
("GR", "Central Macedonia", "GR10"),                                                
("GR", "Crete", "GR13"),                                                            
("GR", "Eastern Macedonia", "GR11"),                                                
("GR", "Eastern Peloponnese", "GR03"),                                              
("GR", "Eastern Sterea Ellada", "GR07"),                                            
("GR", "Epirus", "GR05"),                                                           
("GR", "Northern Peloponnese", "GR02"),                                             
("GR", "Thessalia", "GR08"),                                                        
("GR", "Thrace", "GR12"),                                                           
("GR", "Western Macedonia", "GR09"),                                                
("GR", "Western Peloponnese", "GR01"),                                              
("GR", "Western Sterea Ellada", "GR04"),                                            
("HU", "Danube", "HU1000"),                                                         
("IE", "Eastern", "IEEA"),                                                          
("IE", "Neagh Bann", "GBNIIENB"),                                                   
("IE", "North Western", "GBNIIENW"),                                                
("IE", "Shannon", "IEGBNISH"),                                                      
("IE", "South Eastern", "IESE"),                                                    
("IE", "South Western", "IESW"),                                                    
("IE", "Western", "IEWE"),                                                          
("IT", "Eastern Alps", "ITA"),                                                      
("IT", "Middle Appenines", "ITE"),                                                  
("IT", "Northern Appenines", "ITC"),                                                
("IT", "Po Basin", "ITB"),                                                          
("IT", "Sardinia", "ITG"),                                                          
("IT", "Serchio", "ITD"),                                                           
("IT", "Sicily", "ITH"),                                                            
("IT", "Southern Appenines", "ITF"),                                                
("LT", "Daugava", "LT4500"),                                                        
("LT", "Lielupe", "LT3400"),                                                        
("LT", "Nemunas", "LT1100"),                                                        
("LT", "Venta", "LT2300"),                                                          
("LU", "Meuse", "LU7000"),                                                          
("LU", "Rhine", "LU2000"),                                                          
("LV", "Daugava", "LVDUBA"),                                                        
("LV", "Gauja", "LVGUBA"),                                                          
("LV", "Lielupe", "LVLUBA"),                                                        
("LV", "Venta", "LVVUBA"),                                                          
("MT", "Malta", "MTMalta"),                                                         
("NL", "Ems", "NLEM"),                                                              
("NL", "Meuse", "NLMS"),                                                            
("NL", "Rhine", "NLRN"),                                                            
("NL", "Scheldt", "NLSC"),                                                          
("NO", "Bothnian Bay", "NOSEFI1"),                                                  
("NO", "Bothnian Sea", "NOSE2"),                                                    
("NO", "Finnmark", "NO1105"),                                                       
("NO", "Glomma", "NO5101"),                                                         
("NO", "Kemijoki", "NOFIVHA5"),                                                     
("NO", "Moere and Romsdal", "NO1101"),                                              
("NO", "Nordland", "NO1103"),                                                       
("NO", "Skagerrak and Kattegat", "NOSE5"),                                          
("NO", "South West", "NO5103"),                                                     
("NO", "Tornionjoen (Finnish part)", "NOFIVHA6"),                                   
("NO", "Troendelag", "NO1102"),                                                     
("NO", "Troms", "NO1104"),                                                          
("NO", "West Bay", "NO5102"),                                                       
("NO", "West", "NO5104"),                                                           
("PL", "Danube", "PL1000"),                                                         
("PL", "Dniestr", "PL9000"),                                                        
("PL", "Elbe", "PL5000"),                                                           
("PL", "Jarft", "PL4000"),                                                          
("PL", "Nemunas", "PL8000"),                                                        
("PL", "Odra", "PL6000"),                                                           
("PL", "Pregolya", "PL7000"),                                                       
("PL", "Swieza", "PL3000"),                                                         
("PL", "Ucker", "PL6700"),                                                          
("PL", "Vistula", "PL2000"),                                                        
("PT", "Algarve Basins", "PTRH8"),                                                  
("PT", "Azores", "PTRH9"),                                                          
("PT", "Cavado, Ave and Leca", "PTRH2"),                                            
("PT", "Douro", "PTRH3"),                                                           
("PT", "Guadiana", "PTRH7"),                                                        
("PT", "Madeira", "PTRH10"),
("PT", "Minho and Lima", "PTRH1"),
("PT", "Sado and Mira", "PTRH6"),
("PT", "Tagus and Western Basins", "PTRH5"),
("PT", "Vouga, Mondego and Lis", "PTRH4"),
("RO", "Danube", "RO1000"),
("SE", "Bothnian Bay", "SE1"),
("SE", "Bothnian Sea", "SE2"),
("SE", "Glomma", "SENO5101"),
("SE", "Nordland", "SENO1103"),
("SE", "North Baltic", "SE3"),
("SE", "Skagerrak and Kattegat", "SE5"),
("SE", "South Baltic", "SE4"),
("SE", "Troendelag", "SENO1102"),
("SE", "Troms", "SENO1104"),
("SI", "Danube", "SI_RBD_1"),
("SI", "North Adriatic", "SI_RBD_2"),
("SK", "Danube", "SK40000"),
("SK", "Vistula", "SK30000"),
("GB", "Anglian", "UK05"),
("GB", "Dee", "UK11"),
("GB", "Gibraltar", "UKGI17"),
("GB", "Humber", "UK04"),
("GB", "Neagh Bann", "GBNIIENB"),
("GB", "North Eastern", "GBNINE"),
("GB", "Northumbria", "UK03"),
("GB", "North Western", "GBNIIENW"),
("GB", "North West", "UK12"),
("GB", "Scotland", "UK01"),
("GB", "Severn", "UK09"),
("GB", "Shannon", "UKIEGBNISH"),
("GB", "Solway Tweed", "UK02"),
("GB", "South East", "UK07"),
("GB", "South West", "UK08"),
("GB", "Thames", "UK06"),
("GB", "Western Wales", "UK10"),
]
